language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip

before_script:
  - FIXED=$(go fmt ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "gofmt - $FIXED file(s) not formatted correctly, please run gofmt to fix this." && exit 1; fi

script:
  - go test -v ./niftycloud/
  - go test -v ./compute/
